# Generated by Django 4.2.3 on 2023-12-15 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
            options={"verbose_name_plural": "2. Course Categories",},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=1000)),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=100)),
                ("mobile_no", models.CharField(max_length=20)),
                ("address", models.TextField(max_length=100)),
                ("interested_categories", models.TextField()),
            ],
            options={"verbose_name_plural": "5. Student",},
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=1000)),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=100)),
                ("mobile_no", models.CharField(max_length=20)),
                ("address", models.TextField()),
            ],
            options={"verbose_name_plural": "1. Teacher",},
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "featured_img",
                    models.ImageField(null=True, upload_to="course_imgs/"),
                ),
                ("techs", models.TextField(null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.coursecategory",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.teacher"
                    ),
                ),
            ],
            options={"verbose_name_plural": "3. Courses",},
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("file", models.FileField(null=True, upload_to="chapter_file/")),
                ("remarks", models.TextField(null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.course"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.teacher"
                    ),
                ),
            ],
            options={"verbose_name_plural": "4. Chapters",},
        ),
    ]
